<?xml version="1.0" encoding="UTF-8"?>

<!-- DOCTYPE-->

<!DOCTYPE etiqueta SYSTEM "nota2.dtd" [
    
    <!-- DTD INTERNO-->
    <!-- <!ELEMENT etiqueta (nombre, calle, ciudad, pais, codigo)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
-->

]>

<etiqueta>
    <nombre>Roberto García</nombre>
    <calle>C/ Mayor, 27</calle>
    <ciudad>Córdoba</ciudad>
    <pais>España</pais>
    <codigo>14007</codigo>
</etiqueta>